name: gymbros
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  supabase_flutter: ^2.5.2
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0
  provider: ^6.1.5+1
  image_picker: ^1.2.0
  intl: ^0.20.2
  collection: ^1.19.1
  google_fonts: ^6.3.2
  flutter_local_notifications: ^19.5.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  firebase_auth_mocks: ^0.14.2
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  mocktail: ^1.0.3
  firebase_core_platform_interface: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logoIcon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/launcherIcon.png"


flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/images/logofull.png
